### ISSUE TITLE
White page: navbar_header_profile_list_after.

### ISSUE THREAD

**Issue by SpIdErPiGgY1984** [Flerex/linkedaccounts#13]
Error in: navbar_header_profile_list_after.html

`[Sun Dec 16 14:53:18.881866 2018] [fcgid:warn] [pid 25572:tid 140534261733120] [client 2a02:a03f:56f5:d700:d099:e7e1:46:aebc:51488] mod_fcgid: stderr: #5 /var/www/vhosts/solidjeuh.be/httpdocs/phpbb/template/twig/en in /var/www/vhosts/solidjeuh.be/httpdocs/ext/flerex/linkedaccounts/styles/prosilver/template/event/navbar_header_profile_list_after.html on line 12`

`<a %} %} S_LINKEDACCOUNTS_AJAX data-ajax="flerex.linked_accounts.switch" data-refresh="true" endif
			   href="{{ account.SWITCH_LINK }}" if role="menuitem" {% {%>`

**Comment by Flerex** [comment]
I'm sorry but I can't seem to reproduce your problem. Have you tried doing a fresh installation in a local server?

**Comment by SpIdErPiGgY1984** [comment]
Yes, same error. This line is wrong:

<a %} %} S_LINKEDACCOUNTS_AJAX data-ajax="flerex.linked_accounts.switch" data-refresh="true" endif href="{{ account.SWITCH_LINK }}" if role="menuitem" {% {%>

In your github version, not the one on phpbb.com

[https://github.com/Flerex/linkedaccounts/blob/master/styles/prosilver/template/event/navbar_header_profile_list_after.html#L11](url)

**Comment by Flerex** [comment]
Yeah, right. My bad. I thought you were talking about a release.

Should be fixed!

Thanks for pointing it out.

**Comment by SpIdErPiGgY1984** [comment]
I like to test things 😄
