### ISSUE TITLE
Script path now being ignored

### ISSUE THREAD

**Issue by ianhiddleston** [Flerex/linkedaccounts#20]
Heya, we've been using this extension for a while, however, after updating from 1.2.1 to 1.2.4 we're now having issues with the URL generated to redirect the user after a role switch.

Essentially instead of ending up at:
www.example.com/boards/(blah)

The redirect sends the user to:
www.example.com/(blah)

The rest of phpBB handles the scripting subdirectory fine, so there may still be some work to do on the url generation stuff.

Ian

**Comment by Flerex** [comment]
Sorry for the delay.

Do you have the AJAX setting enabled? Does it happen with the option disabled?

Thank you.

**Comment by Flerex** [comment]
This should be fixed in 1.3.0.

Thanks for reporting.
