### ISSUE TITLE
Got this error

### ISSUE THREAD

**Issue by miri4ever** [Flerex/linkedaccounts#26]
I got this error if AJAX is off:

Fatal error: Uncaught TypeError: Argument 2 passed to flerex\linkedaccounts\controller\switcher::__construct() must be an instance of phpbb\auth\auth, instance of phpbb\config\db given

If Ajax is on nothing happens and no switch.

**Comment by Flerex** [comment]
You are correct. I don't know how I didn't catch that.

Thank you!

Fixed in the latest release.
