### ISSUE TITLE
Missing URL / ?

### ISSUE THREAD

**Issue by miri4ever** [Flerex/linkedaccounts#27]
After now successfully switched I got this.

With AJAX on:

File not found

http://www.page.com/FORUMindex.php

After addng myself the missing / it works.

With AJAX off:

Not Found
The requested URL /FORUMswitchaccount/4 was not found on this server.

http://www.url.com/FORUMswitchaccount/4?sid=695

Also missing / here. After I put in II got Accounts succfully switched and after this message is gone, this message came up:

Du kannst nicht zu diesem Account wechseln. / You cant switch to this Account.

But this kind of behave existed in earlier versions too, even iif accounts was switched thiis message always came up. With AJAX on this will not be shown.

I tested to add / to my Board URL, but it did not help to fix this behave, if II maybe did something wrong iin my settings. Just to be sure before reporting here.

**Comment by Flerex** [comment]
Both should be fixed!

Thanks again. 💙
