### ISSUE TITLE
Compatibility issue with Comboot Theme

### ISSUE THREAD

**Issue by windwolfr** [Flerex/linkedaccounts#8]
Using the latest release of linkedaccounts with the Comboot theme's latest release lead to an error 500 when trying to load the linked accounts tab in the UCP.

You can access the Comboot repo by signing up here:
https://comboot.io/blog/beta/beta-3-1/

and the repo is here:
https://github.com/ComBoot/ComBoot-3.1

**Comment by Flerex** [comment]
Hello,

In theory the style shouldn't be able to make the extension malfunction. Please check if it the same is happening with Prosilver. If it is not, then most likely it's something the style author should fix.

Anyway, I don't mind checking it out if you provide a download link, but I don't actually want to sign up in any kind of website for security reasons. I hope you understand.

Best regards.

**Comment by windwolfr** [comment]
I've figured it out, it's because your extension special page isn't inherited by default into new styles, to solve this I copied the prosilver one packed in your extension and will be modifying it to fit the comboot style.

As a precaution, I'd suggest adding to the install instructions that any style that malfunctions should be set to inherit from prosilver.

**Comment by Flerex** [comment]
I'm afraid that's the default behavior of all phpBB extensions. If I'm not mistaken, even phpBB's own official extension will have some sort of problem with styles that do not inherit from prosilver. I just checked the “Board Rules” and “Pages” official extensions and I think the same would happen with them.

Anyway, I already had a FAQ extension in the extensions database for this kind of problems. You might wanna check it out:

[The extension doesn't look right in my forum's style.](https://www.phpbb.com/customise/db/extension/linked_accounts/faq/2581)
